### PR TITLE
Transparent Background and Saturation... And Transformations and Icons and Transparency Bug Fix

### PR DESCRIPTION
**Pull request by jspayd**
I realize now that it might not be intended for JEIE to support transparent images, but I left the background in there just in case. If support for transparent images is intended, then some changes need to be made. There is a bug when editing a semi-transparent image: if an effect is applied to the image, the original image is still drawn below because the effect only affects the cache and not the raster.

### CODE REVIEW

**Comment by IsmAvatar** [comment]
As this is intended to be an image editor for lgm and by extension gm, and since both of those programs support transparency and partial transparency, then this image editor should provide easy tools for transparency and partial.

**Comment by JoshDreamland** [comment]
Hi! What icon pack are those images you uploaded from? I'm interested in the license on them.

Also, I noticed you changed ImageAction from an interface to an abstract class. It seems that you did so just to incorporate the property "copiesRaster," which could just as easily have been made a function and not defaulted (since it's a one-line implement, or four if the implementer is OCD). Was there some more profound reason for this change that I am missing? I'd prefer that it be left an interface for purely semantic reasons, and I imagine Ism would agree.

Aside from those two concerns, I have no aversion to pulling this.

**Comment by jspayd** [comment]
I got some of the icons from the Nuvola icon set, the same one that was already being used. I made the rest. I guess I just hadn't thought of making copiesRaster a function. I'll fix that and commit.

**Comment by jspayd** [comment]
I made it an interface again, but I discovered that shouldDrawRaster doesn't work when there is more than one action that copies the raster and I can't seem to fix it. I remember checking many different scenarios when I first implemented the function and I don't remember this being a problem.

**Comment by jspayd** [comment]
I fixed the bug. shouldDrawRaster actually was working, but the cache was never cleared before redrawing the image over it.

**Comment by JoshDreamland** [comment]
Thanks.

IsmAvatar: I have no further reasons not to pull this. I'll leave it up to you, as I don't know how well you looked over it, but now there are fewer changes to review.

**Comment by IsmAvatar** [comment]
Thanks for the debrief, Josh.

I've reviewed these changes (albeit not as thoroughly as I would love to, if I had the time) and I'd say they look really good. The code looks sound, and ready to be pulled, my only concern is updating copyrights - needs to be done. The files that you have modified (more than a line of code) should bear your own copyright in addition to the other contributors to the files (as a rule of thumb, main contributor is listed first - simply because they know the code the best, so should any questions arise, a person would pull their name and email first). New files that you have contributed must bear the same copyright mark as the other files, with only your name listed under copyright. Images should have their own copyright file indicating where they came from and crediting their proper author (or in the case of the Nuvela icons, that information should already exist, so you simply need to add the names of new icons next to the existing names). The formats for all of these should be fairly obvious.

It might sound trivial (and even bureaucratic), but licensing info is extremely important in the potential implications if you don't do it.

**Comment by jspayd** [comment]
I added the copyright notices. About the commit before (Removed incorrect notice from file.), I had originally copied a file to use as a guide, but ended up deleting everything and writing all of my own code. I also noticed that some other files don't have copyright notices on them, but I didn't add them because I don't think I can say something was copyrighted by someone else.

**Pull request merged**
